/* Generated by Yosys 0.39 (git sha1 00338082b, aarch64-apple-darwin21.4-clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* hdlname = "axis_i2s2" *)
(* src = "axis_i2s2.v:24.8-24.17" *)
module axis_i2s2(axis_clk, axis_resetn, tx_axis_c_valid, tx_axis_c_ready, tx_axis_c_last, rx_axis_p_valid, rx_axis_p_ready, rx_axis_p_last, tx_mclk, tx_lrck, tx_sclk, tx_sdout, rx_mclk, rx_lrck, rx_sclk, rx_sdin, rx_axis_p_data, tx_axis_c_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  (* force_downto = 32'd1 *)
  (* src = "axis_i2s2.v:51.18-51.27|/opt/tabby/libexec/../share/yosys/techmap.v:270.23-270.24" *)
  wire [8:0] _113_;
  (* force_downto = 32'd1 *)
  (* src = "axis_i2s2.v:51.18-51.27|/opt/tabby/libexec/../share/yosys/techmap.v:270.26-270.27" *)
  wire [8:0] _114_;
  (* src = "axis_i2s2.v:25.24-25.32" *)
  input axis_clk;
  wire axis_clk;
  (* src = "axis_i2s2.v:26.24-26.35" *)
  input axis_resetn;
  wire axis_resetn;
  (* src = "axis_i2s2.v:47.15-47.20" *)
  reg [8:0] count = 9'h000;
  (* src = "axis_i2s2.v:113.10-113.18" *)
  wire din_sync;
  (* src = "axis_i2s2.v:112.15-112.29" *)
  reg [2:0] din_sync_shift = 3'h0;
  (* src = "axis_i2s2.v:53.10-53.14" *)
  wire lrck;
  (* src = "axis_i2s2.v:55.10-55.14" *)
  wire mclk;
  (* src = "axis_i2s2.v:33.24-33.38" *)
  output [31:0] rx_axis_p_data;
  wire [31:0] rx_axis_p_data;
  (* src = "axis_i2s2.v:36.24-36.38" *)
  output rx_axis_p_last;
  reg rx_axis_p_last = 1'h0;
  (* src = "axis_i2s2.v:35.24-35.39" *)
  input rx_axis_p_ready;
  wire rx_axis_p_ready;
  (* src = "axis_i2s2.v:34.24-34.39" *)
  output rx_axis_p_valid;
  reg rx_axis_p_valid = 1'h0;
  (* init = 32'hxx000000 *)
  (* src = "axis_i2s2.v:128.16-128.25" *)
  wire [31:0] rx_data_l;
  (* src = "axis_i2s2.v:118.16-118.31" *)
  reg [23:0] rx_data_l_shift = 24'h000000;
  (* init = 32'hxx000000 *)
  (* src = "axis_i2s2.v:129.16-129.25" *)
  wire [31:0] rx_data_r;
  (* src = "axis_i2s2.v:119.16-119.31" *)
  reg [23:0] rx_data_r_shift = 24'h000000;
  (* src = "axis_i2s2.v:43.17-43.24" *)
  output rx_lrck;
  wire rx_lrck;
  (* src = "axis_i2s2.v:42.17-42.24" *)
  output rx_mclk;
  wire rx_mclk;
  (* src = "axis_i2s2.v:44.17-44.24" *)
  output rx_sclk;
  wire rx_sclk;
  (* src = "axis_i2s2.v:45.17-45.24" *)
  input rx_sdin;
  wire rx_sdin;
  (* src = "axis_i2s2.v:54.10-54.14" *)
  wire sclk;
  (* src = "axis_i2s2.v:28.24-28.38" *)
  input [31:0] tx_axis_c_data;
  wire [31:0] tx_axis_c_data;
  (* src = "axis_i2s2.v:31.24-31.38" *)
  input tx_axis_c_last;
  wire tx_axis_c_last;
  (* src = "axis_i2s2.v:30.24-30.39" *)
  output tx_axis_c_ready;
  reg tx_axis_c_ready = 1'h0;
  (* src = "axis_i2s2.v:29.24-29.39" *)
  input tx_axis_c_valid;
  wire tx_axis_c_valid;
  (* init = 32'hxx000000 *)
  (* src = "axis_i2s2.v:64.16-64.25" *)
  wire [31:0] tx_data_l;
  (* src = "axis_i2s2.v:88.16-88.31" *)
  reg [23:0] tx_data_l_shift = 24'h000000;
  (* init = 32'hxx000000 *)
  (* src = "axis_i2s2.v:65.16-65.25" *)
  wire [31:0] tx_data_r;
  (* src = "axis_i2s2.v:89.16-89.31" *)
  reg [23:0] tx_data_r_shift = 24'h000000;
  (* src = "axis_i2s2.v:39.17-39.24" *)
  output tx_lrck;
  wire tx_lrck;
  (* src = "axis_i2s2.v:38.17-38.24" *)
  output tx_mclk;
  wire tx_mclk;
  (* src = "axis_i2s2.v:40.17-40.24" *)
  output tx_sclk;
  wire tx_sclk;
  (* src = "axis_i2s2.v:41.17-41.25" *)
  output tx_sdout;
  wire tx_sdout;
  assign _113_[0] = ~count[0];
  assign _010_ = ~(tx_axis_c_valid & tx_axis_c_ready);
  assign _004_ = ~(_010_ | tx_axis_c_last);
  assign _011_ = ~count[8];
  assign _012_ = ~(count[1] & count[0]);
  assign _013_ = count[3] | ~(count[2]);
  assign _014_ = _013_ | _012_;
  assign _015_ = count[5] | count[4];
  assign _016_ = count[6] | count[7];
  assign _017_ = _016_ | _015_;
  assign _018_ = _017_ | _014_;
  assign _019_ = _011_ & ~(_018_);
  assign _020_ = count[2] & ~(_012_);
  assign _021_ = ~count[7];
  assign _022_ = count[4] | ~(count[3]);
  assign _023_ = count[6] | count[5];
  assign _024_ = _023_ | _022_;
  assign _025_ = _021_ & ~(_024_);
  assign _026_ = ~(_025_ | _017_);
  assign _027_ = _020_ & ~(_026_);
  assign _028_ = count[6] & ~(count[5]);
  assign _029_ = count[4] | count[3];
  assign _030_ = _028_ & ~(_029_);
  assign _031_ = ~(_030_ & count[7]);
  assign _032_ = _030_ | ~(count[6]);
  assign _033_ = _032_ | _021_;
  assign _034_ = _031_ & ~(_033_);
  assign _035_ = _027_ & ~(_034_);
  assign _036_ = _019_ | ~(_035_);
  assign _037_ = _036_ | _011_;
  assign _038_ = ~(_035_ | _019_);
  assign _003_ = _037_ & ~(_038_);
  assign _002_ = tx_axis_c_last & ~(_010_);
  assign _039_ = ~_018_;
  assign _001_ = count[8] ? _035_ : _039_;
  assign _040_ = ~axis_resetn;
  assign _041_ = _002_ | _040_;
  assign _042_ = count[1] | count[0];
  assign _043_ = count[2] | count[3];
  assign _044_ = _043_ | _042_;
  assign _045_ = _044_ | _017_;
  assign _046_ = _011_ & ~(_045_);
  assign _007_ = _046_ | _041_;
  assign _047_ = _012_ | count[2];
  assign _048_ = _047_ | _034_;
  assign _049_ = _048_ | _026_;
  assign _005_ = count[8] & ~(_049_);
  assign _006_ = _011_ & ~(_049_);
  assign _050_ = ~(count[6] & count[7]);
  assign _051_ = _050_ | _015_;
  assign _052_ = _051_ | _014_;
  assign _009_ = _052_ | _011_;
  assign _064_ = ~(_009_ | rx_axis_p_valid);
  assign _066_ = ~rx_axis_p_last;
  assign _065_ = rx_axis_p_ready & rx_axis_p_valid;
  assign _053_ = _065_ & ~(_066_);
  assign _000_ = _053_ | _064_;
  assign _008_ = _064_ | _040_;
  assign _077_ = _019_ ? tx_data_l[1] : tx_data_l_shift[0];
  assign _082_ = _019_ ? tx_data_l[2] : tx_data_l_shift[1];
  assign _083_ = _019_ ? tx_data_l[3] : tx_data_l_shift[2];
  assign _084_ = _019_ ? tx_data_l[4] : tx_data_l_shift[3];
  assign _085_ = _019_ ? tx_data_l[5] : tx_data_l_shift[4];
  assign _086_ = _019_ ? tx_data_l[6] : tx_data_l_shift[5];
  assign _087_ = _019_ ? tx_data_l[7] : tx_data_l_shift[6];
  assign _088_ = _019_ ? tx_data_l[8] : tx_data_l_shift[7];
  assign _089_ = _019_ ? tx_data_l[9] : tx_data_l_shift[8];
  assign _067_ = _019_ ? tx_data_l[10] : tx_data_l_shift[9];
  assign _068_ = _019_ ? tx_data_l[11] : tx_data_l_shift[10];
  assign _069_ = _019_ ? tx_data_l[12] : tx_data_l_shift[11];
  assign _070_ = _019_ ? tx_data_l[13] : tx_data_l_shift[12];
  assign _071_ = _019_ ? tx_data_l[14] : tx_data_l_shift[13];
  assign _072_ = _019_ ? tx_data_l[15] : tx_data_l_shift[14];
  assign _073_ = _019_ ? tx_data_l[16] : tx_data_l_shift[15];
  assign _074_ = _019_ ? tx_data_l[17] : tx_data_l_shift[16];
  assign _075_ = _019_ ? tx_data_l[18] : tx_data_l_shift[17];
  assign _076_ = _019_ ? tx_data_l[19] : tx_data_l_shift[18];
  assign _078_ = _019_ ? tx_data_l[20] : tx_data_l_shift[19];
  assign _079_ = _019_ ? tx_data_l[21] : tx_data_l_shift[20];
  assign _080_ = _019_ ? tx_data_l[22] : tx_data_l_shift[21];
  assign _081_ = _019_ ? tx_data_l[23] : tx_data_l_shift[22];
  assign _100_ = _019_ ? tx_data_r[1] : tx_data_r_shift[0];
  assign _105_ = _019_ ? tx_data_r[2] : tx_data_r_shift[1];
  assign _106_ = _019_ ? tx_data_r[3] : tx_data_r_shift[2];
  assign _107_ = _019_ ? tx_data_r[4] : tx_data_r_shift[3];
  assign _108_ = _019_ ? tx_data_r[5] : tx_data_r_shift[4];
  assign _109_ = _019_ ? tx_data_r[6] : tx_data_r_shift[5];
  assign _110_ = _019_ ? tx_data_r[7] : tx_data_r_shift[6];
  assign _111_ = _019_ ? tx_data_r[8] : tx_data_r_shift[7];
  assign _112_ = _019_ ? tx_data_r[9] : tx_data_r_shift[8];
  assign _090_ = _019_ ? tx_data_r[10] : tx_data_r_shift[9];
  assign _091_ = _019_ ? tx_data_r[11] : tx_data_r_shift[10];
  assign _092_ = _019_ ? tx_data_r[12] : tx_data_r_shift[11];
  assign _093_ = _019_ ? tx_data_r[13] : tx_data_r_shift[12];
  assign _094_ = _019_ ? tx_data_r[14] : tx_data_r_shift[13];
  assign _095_ = _019_ ? tx_data_r[15] : tx_data_r_shift[14];
  assign _096_ = _019_ ? tx_data_r[16] : tx_data_r_shift[15];
  assign _097_ = _019_ ? tx_data_r[17] : tx_data_r_shift[16];
  assign _098_ = _019_ ? tx_data_r[18] : tx_data_r_shift[17];
  assign _099_ = _019_ ? tx_data_r[19] : tx_data_r_shift[18];
  assign _101_ = _019_ ? tx_data_r[20] : tx_data_r_shift[19];
  assign _102_ = _019_ ? tx_data_r[21] : tx_data_r_shift[20];
  assign _103_ = _019_ ? tx_data_r[22] : tx_data_r_shift[21];
  assign _104_ = _019_ ? tx_data_r[23] : tx_data_r_shift[22];
  assign rx_axis_p_data[0] = rx_axis_p_last ? rx_data_r[0] : rx_data_l[0];
  assign rx_axis_p_data[1] = rx_axis_p_last ? rx_data_r[1] : rx_data_l[1];
  assign rx_axis_p_data[2] = rx_axis_p_last ? rx_data_r[2] : rx_data_l[2];
  assign rx_axis_p_data[3] = rx_axis_p_last ? rx_data_r[3] : rx_data_l[3];
  assign rx_axis_p_data[4] = rx_axis_p_last ? rx_data_r[4] : rx_data_l[4];
  assign rx_axis_p_data[5] = rx_axis_p_last ? rx_data_r[5] : rx_data_l[5];
  assign rx_axis_p_data[6] = rx_axis_p_last ? rx_data_r[6] : rx_data_l[6];
  assign rx_axis_p_data[7] = rx_axis_p_last ? rx_data_r[7] : rx_data_l[7];
  assign rx_axis_p_data[8] = rx_axis_p_last ? rx_data_r[8] : rx_data_l[8];
  assign rx_axis_p_data[9] = rx_axis_p_last ? rx_data_r[9] : rx_data_l[9];
  assign rx_axis_p_data[10] = rx_axis_p_last ? rx_data_r[10] : rx_data_l[10];
  assign rx_axis_p_data[11] = rx_axis_p_last ? rx_data_r[11] : rx_data_l[11];
  assign rx_axis_p_data[12] = rx_axis_p_last ? rx_data_r[12] : rx_data_l[12];
  assign rx_axis_p_data[13] = rx_axis_p_last ? rx_data_r[13] : rx_data_l[13];
  assign rx_axis_p_data[14] = rx_axis_p_last ? rx_data_r[14] : rx_data_l[14];
  assign rx_axis_p_data[15] = rx_axis_p_last ? rx_data_r[15] : rx_data_l[15];
  assign rx_axis_p_data[16] = rx_axis_p_last ? rx_data_r[16] : rx_data_l[16];
  assign rx_axis_p_data[17] = rx_axis_p_last ? rx_data_r[17] : rx_data_l[17];
  assign rx_axis_p_data[18] = rx_axis_p_last ? rx_data_r[18] : rx_data_l[18];
  assign rx_axis_p_data[19] = rx_axis_p_last ? rx_data_r[19] : rx_data_l[19];
  assign rx_axis_p_data[20] = rx_axis_p_last ? rx_data_r[20] : rx_data_l[20];
  assign rx_axis_p_data[21] = rx_axis_p_last ? rx_data_r[21] : rx_data_l[21];
  assign rx_axis_p_data[22] = rx_axis_p_last ? rx_data_r[22] : rx_data_l[22];
  assign rx_axis_p_data[23] = rx_axis_p_last ? rx_data_r[23] : rx_data_l[23];
  assign _054_ = _034_ | _026_;
  assign _055_ = count[8] ? tx_data_r_shift[23] : tx_data_l_shift[23];
  assign tx_sdout = _055_ & ~(_054_);
  assign _114_[1] = count[1] ^ count[0];
  assign _114_[2] = ~(_012_ ^ count[2]);
  assign _114_[3] = _020_ ^ count[3];
  assign _056_ = ~(count[2] & count[3]);
  assign _057_ = ~(_056_ | _012_);
  assign _114_[4] = _057_ ^ count[4];
  assign _058_ = _057_ & count[4];
  assign _114_[5] = _058_ ^ count[5];
  assign _059_ = ~(count[5] & count[4]);
  assign _060_ = _059_ | ~(_057_);
  assign _114_[6] = ~(_060_ ^ count[6]);
  assign _061_ = count[6] & ~(_060_);
  assign _114_[7] = _061_ ^ count[7];
  assign _062_ = _059_ | _050_;
  assign _063_ = _057_ & ~(_062_);
  assign _114_[8] = _063_ ^ count[8];
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_)
      if (!_019_) tx_data_l_shift[0] <= 1'h0;
      else tx_data_l_shift[0] <= tx_data_l[0];
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[1] <= _077_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[2] <= _082_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[3] <= _083_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[4] <= _084_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[5] <= _085_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[6] <= _086_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[7] <= _087_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[8] <= _088_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[9] <= _089_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[10] <= _067_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[11] <= _068_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[12] <= _069_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[13] <= _070_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[14] <= _071_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[15] <= _072_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[16] <= _073_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[17] <= _074_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[18] <= _075_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[19] <= _076_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[20] <= _078_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[21] <= _079_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[22] <= _080_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_003_) tx_data_l_shift[23] <= _081_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[1] <= _100_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[2] <= _105_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[3] <= _106_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[4] <= _107_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[5] <= _108_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[6] <= _109_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[7] <= _110_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[8] <= _111_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[9] <= _112_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[10] <= _090_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[11] <= _091_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[12] <= _092_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[13] <= _093_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[14] <= _094_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[15] <= _095_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[16] <= _096_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[17] <= _097_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[18] <= _098_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[19] <= _099_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[20] <= _101_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[21] <= _102_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[22] <= _103_;
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_) tx_data_r_shift[23] <= _104_;
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[0] <= _113_[0];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[1] <= _114_[1];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[2] <= _114_[2];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[3] <= _114_[3];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[4] <= _114_[4];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[5] <= _114_[5];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[6] <= _114_[6];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[7] <= _114_[7];
  (* src = "axis_i2s2.v:50.11-51.28" *)
  always @(posedge axis_clk)
    count[8] <= _114_[8];
  (* src = "axis_i2s2.v:67.11-75.37" *)
  always @(posedge axis_clk)
    if (_007_) tx_axis_c_ready <= 1'h0;
    else if (!_009_) tx_axis_c_ready <= 1'h1;
  reg \tx_data_r_reg[0]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[0]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[0]  <= tx_axis_c_data[0];
  assign tx_data_r[0] = \tx_data_r_reg[0] ;
  reg \tx_data_r_reg[1]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[1]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[1]  <= tx_axis_c_data[1];
  assign tx_data_r[1] = \tx_data_r_reg[1] ;
  reg \tx_data_r_reg[2]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[2]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[2]  <= tx_axis_c_data[2];
  assign tx_data_r[2] = \tx_data_r_reg[2] ;
  reg \tx_data_r_reg[3]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[3]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[3]  <= tx_axis_c_data[3];
  assign tx_data_r[3] = \tx_data_r_reg[3] ;
  reg \tx_data_r_reg[4]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[4]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[4]  <= tx_axis_c_data[4];
  assign tx_data_r[4] = \tx_data_r_reg[4] ;
  reg \tx_data_r_reg[5]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[5]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[5]  <= tx_axis_c_data[5];
  assign tx_data_r[5] = \tx_data_r_reg[5] ;
  reg \tx_data_r_reg[6]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[6]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[6]  <= tx_axis_c_data[6];
  assign tx_data_r[6] = \tx_data_r_reg[6] ;
  reg \tx_data_r_reg[7]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[7]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[7]  <= tx_axis_c_data[7];
  assign tx_data_r[7] = \tx_data_r_reg[7] ;
  reg \tx_data_r_reg[8]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[8]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[8]  <= tx_axis_c_data[8];
  assign tx_data_r[8] = \tx_data_r_reg[8] ;
  reg \tx_data_r_reg[9]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[9]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[9]  <= tx_axis_c_data[9];
  assign tx_data_r[9] = \tx_data_r_reg[9] ;
  reg \tx_data_r_reg[10]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[10]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[10]  <= tx_axis_c_data[10];
  assign tx_data_r[10] = \tx_data_r_reg[10] ;
  reg \tx_data_r_reg[11]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[11]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[11]  <= tx_axis_c_data[11];
  assign tx_data_r[11] = \tx_data_r_reg[11] ;
  reg \tx_data_r_reg[12]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[12]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[12]  <= tx_axis_c_data[12];
  assign tx_data_r[12] = \tx_data_r_reg[12] ;
  reg \tx_data_r_reg[13]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[13]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[13]  <= tx_axis_c_data[13];
  assign tx_data_r[13] = \tx_data_r_reg[13] ;
  reg \tx_data_r_reg[14]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[14]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[14]  <= tx_axis_c_data[14];
  assign tx_data_r[14] = \tx_data_r_reg[14] ;
  reg \tx_data_r_reg[15]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[15]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[15]  <= tx_axis_c_data[15];
  assign tx_data_r[15] = \tx_data_r_reg[15] ;
  reg \tx_data_r_reg[16]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[16]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[16]  <= tx_axis_c_data[16];
  assign tx_data_r[16] = \tx_data_r_reg[16] ;
  reg \tx_data_r_reg[17]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[17]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[17]  <= tx_axis_c_data[17];
  assign tx_data_r[17] = \tx_data_r_reg[17] ;
  reg \tx_data_r_reg[18]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[18]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[18]  <= tx_axis_c_data[18];
  assign tx_data_r[18] = \tx_data_r_reg[18] ;
  reg \tx_data_r_reg[19]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[19]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[19]  <= tx_axis_c_data[19];
  assign tx_data_r[19] = \tx_data_r_reg[19] ;
  reg \tx_data_r_reg[20]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[20]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[20]  <= tx_axis_c_data[20];
  assign tx_data_r[20] = \tx_data_r_reg[20] ;
  reg \tx_data_r_reg[21]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[21]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[21]  <= tx_axis_c_data[21];
  assign tx_data_r[21] = \tx_data_r_reg[21] ;
  reg \tx_data_r_reg[22]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[22]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[22]  <= tx_axis_c_data[22];
  assign tx_data_r[22] = \tx_data_r_reg[22] ;
  reg \tx_data_r_reg[23]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_r_reg[23]  <= 1'h0;
    else if (_002_) \tx_data_r_reg[23]  <= tx_axis_c_data[23];
  assign tx_data_r[23] = \tx_data_r_reg[23] ;
  reg \tx_data_l_reg[0]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[0]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[0]  <= tx_axis_c_data[0];
  assign tx_data_l[0] = \tx_data_l_reg[0] ;
  reg \tx_data_l_reg[1]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[1]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[1]  <= tx_axis_c_data[1];
  assign tx_data_l[1] = \tx_data_l_reg[1] ;
  reg \tx_data_l_reg[2]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[2]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[2]  <= tx_axis_c_data[2];
  assign tx_data_l[2] = \tx_data_l_reg[2] ;
  reg \tx_data_l_reg[3]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[3]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[3]  <= tx_axis_c_data[3];
  assign tx_data_l[3] = \tx_data_l_reg[3] ;
  reg \tx_data_l_reg[4]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[4]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[4]  <= tx_axis_c_data[4];
  assign tx_data_l[4] = \tx_data_l_reg[4] ;
  reg \tx_data_l_reg[5]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[5]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[5]  <= tx_axis_c_data[5];
  assign tx_data_l[5] = \tx_data_l_reg[5] ;
  reg \tx_data_l_reg[6]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[6]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[6]  <= tx_axis_c_data[6];
  assign tx_data_l[6] = \tx_data_l_reg[6] ;
  reg \tx_data_l_reg[7]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[7]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[7]  <= tx_axis_c_data[7];
  assign tx_data_l[7] = \tx_data_l_reg[7] ;
  reg \tx_data_l_reg[8]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[8]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[8]  <= tx_axis_c_data[8];
  assign tx_data_l[8] = \tx_data_l_reg[8] ;
  reg \tx_data_l_reg[9]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[9]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[9]  <= tx_axis_c_data[9];
  assign tx_data_l[9] = \tx_data_l_reg[9] ;
  reg \tx_data_l_reg[10]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[10]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[10]  <= tx_axis_c_data[10];
  assign tx_data_l[10] = \tx_data_l_reg[10] ;
  reg \tx_data_l_reg[11]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[11]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[11]  <= tx_axis_c_data[11];
  assign tx_data_l[11] = \tx_data_l_reg[11] ;
  reg \tx_data_l_reg[12]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[12]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[12]  <= tx_axis_c_data[12];
  assign tx_data_l[12] = \tx_data_l_reg[12] ;
  reg \tx_data_l_reg[13]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[13]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[13]  <= tx_axis_c_data[13];
  assign tx_data_l[13] = \tx_data_l_reg[13] ;
  reg \tx_data_l_reg[14]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[14]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[14]  <= tx_axis_c_data[14];
  assign tx_data_l[14] = \tx_data_l_reg[14] ;
  reg \tx_data_l_reg[15]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[15]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[15]  <= tx_axis_c_data[15];
  assign tx_data_l[15] = \tx_data_l_reg[15] ;
  reg \tx_data_l_reg[16]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[16]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[16]  <= tx_axis_c_data[16];
  assign tx_data_l[16] = \tx_data_l_reg[16] ;
  reg \tx_data_l_reg[17]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[17]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[17]  <= tx_axis_c_data[17];
  assign tx_data_l[17] = \tx_data_l_reg[17] ;
  reg \tx_data_l_reg[18]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[18]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[18]  <= tx_axis_c_data[18];
  assign tx_data_l[18] = \tx_data_l_reg[18] ;
  reg \tx_data_l_reg[19]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[19]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[19]  <= tx_axis_c_data[19];
  assign tx_data_l[19] = \tx_data_l_reg[19] ;
  reg \tx_data_l_reg[20]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[20]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[20]  <= tx_axis_c_data[20];
  assign tx_data_l[20] = \tx_data_l_reg[20] ;
  reg \tx_data_l_reg[21]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[21]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[21]  <= tx_axis_c_data[21];
  assign tx_data_l[21] = \tx_data_l_reg[21] ;
  reg \tx_data_l_reg[22]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[22]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[22]  <= tx_axis_c_data[22];
  assign tx_data_l[22] = \tx_data_l_reg[22] ;
  reg \tx_data_l_reg[23]  = 1'h0;
  (* src = "axis_i2s2.v:77.11-85.45" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \tx_data_l_reg[23]  <= 1'h0;
    else if (_004_) \tx_data_l_reg[23]  <= tx_axis_c_data[23];
  assign tx_data_l[23] = \tx_data_l_reg[23] ;
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[0] <= din_sync_shift[2];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[1] <= rx_data_r_shift[0];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[2] <= rx_data_r_shift[1];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[3] <= rx_data_r_shift[2];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[4] <= rx_data_r_shift[3];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[5] <= rx_data_r_shift[4];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[6] <= rx_data_r_shift[5];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[7] <= rx_data_r_shift[6];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[8] <= rx_data_r_shift[7];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[9] <= rx_data_r_shift[8];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[10] <= rx_data_r_shift[9];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[11] <= rx_data_r_shift[10];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[12] <= rx_data_r_shift[11];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[13] <= rx_data_r_shift[12];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[14] <= rx_data_r_shift[13];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[15] <= rx_data_r_shift[14];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[16] <= rx_data_r_shift[15];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[17] <= rx_data_r_shift[16];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[18] <= rx_data_r_shift[17];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[19] <= rx_data_r_shift[18];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[20] <= rx_data_r_shift[19];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[21] <= rx_data_r_shift[20];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[22] <= rx_data_r_shift[21];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_005_) rx_data_r_shift[23] <= rx_data_r_shift[22];
  (* src = "axis_i2s2.v:91.11-100.12" *)
  always @(posedge axis_clk)
    if (_001_)
      if (!_019_) tx_data_r_shift[0] <= 1'h0;
      else tx_data_r_shift[0] <= tx_data_r[0];
  (* src = "axis_i2s2.v:114.11-115.58" *)
  always @(posedge axis_clk)
    din_sync_shift[0] <= rx_sdin;
  (* src = "axis_i2s2.v:114.11-115.58" *)
  always @(posedge axis_clk)
    din_sync_shift[1] <= din_sync_shift[0];
  (* src = "axis_i2s2.v:114.11-115.58" *)
  always @(posedge axis_clk)
    din_sync_shift[2] <= din_sync_shift[1];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[0] <= din_sync_shift[2];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[1] <= rx_data_l_shift[0];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[2] <= rx_data_l_shift[1];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[3] <= rx_data_l_shift[2];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[4] <= rx_data_l_shift[3];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[5] <= rx_data_l_shift[4];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[6] <= rx_data_l_shift[5];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[7] <= rx_data_l_shift[6];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[8] <= rx_data_l_shift[7];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[9] <= rx_data_l_shift[8];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[10] <= rx_data_l_shift[9];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[11] <= rx_data_l_shift[10];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[12] <= rx_data_l_shift[11];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[13] <= rx_data_l_shift[12];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[14] <= rx_data_l_shift[13];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[15] <= rx_data_l_shift[14];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[16] <= rx_data_l_shift[15];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[17] <= rx_data_l_shift[16];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[18] <= rx_data_l_shift[17];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[19] <= rx_data_l_shift[18];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[20] <= rx_data_l_shift[19];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[21] <= rx_data_l_shift[20];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[22] <= rx_data_l_shift[21];
  (* src = "axis_i2s2.v:120.11-125.64" *)
  always @(posedge axis_clk)
    if (_006_) rx_data_l_shift[23] <= rx_data_l_shift[22];
  reg \rx_data_l_reg[0]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[0]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[0]  <= rx_data_l_shift[0];
  assign rx_data_l[0] = \rx_data_l_reg[0] ;
  reg \rx_data_l_reg[1]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[1]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[1]  <= rx_data_l_shift[1];
  assign rx_data_l[1] = \rx_data_l_reg[1] ;
  reg \rx_data_l_reg[2]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[2]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[2]  <= rx_data_l_shift[2];
  assign rx_data_l[2] = \rx_data_l_reg[2] ;
  reg \rx_data_l_reg[3]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[3]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[3]  <= rx_data_l_shift[3];
  assign rx_data_l[3] = \rx_data_l_reg[3] ;
  reg \rx_data_l_reg[4]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[4]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[4]  <= rx_data_l_shift[4];
  assign rx_data_l[4] = \rx_data_l_reg[4] ;
  reg \rx_data_l_reg[5]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[5]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[5]  <= rx_data_l_shift[5];
  assign rx_data_l[5] = \rx_data_l_reg[5] ;
  reg \rx_data_l_reg[6]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[6]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[6]  <= rx_data_l_shift[6];
  assign rx_data_l[6] = \rx_data_l_reg[6] ;
  reg \rx_data_l_reg[7]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[7]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[7]  <= rx_data_l_shift[7];
  assign rx_data_l[7] = \rx_data_l_reg[7] ;
  reg \rx_data_l_reg[8]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[8]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[8]  <= rx_data_l_shift[8];
  assign rx_data_l[8] = \rx_data_l_reg[8] ;
  reg \rx_data_l_reg[9]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[9]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[9]  <= rx_data_l_shift[9];
  assign rx_data_l[9] = \rx_data_l_reg[9] ;
  reg \rx_data_l_reg[10]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[10]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[10]  <= rx_data_l_shift[10];
  assign rx_data_l[10] = \rx_data_l_reg[10] ;
  reg \rx_data_l_reg[11]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[11]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[11]  <= rx_data_l_shift[11];
  assign rx_data_l[11] = \rx_data_l_reg[11] ;
  reg \rx_data_l_reg[12]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[12]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[12]  <= rx_data_l_shift[12];
  assign rx_data_l[12] = \rx_data_l_reg[12] ;
  reg \rx_data_l_reg[13]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[13]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[13]  <= rx_data_l_shift[13];
  assign rx_data_l[13] = \rx_data_l_reg[13] ;
  reg \rx_data_l_reg[14]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[14]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[14]  <= rx_data_l_shift[14];
  assign rx_data_l[14] = \rx_data_l_reg[14] ;
  reg \rx_data_l_reg[15]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[15]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[15]  <= rx_data_l_shift[15];
  assign rx_data_l[15] = \rx_data_l_reg[15] ;
  reg \rx_data_l_reg[16]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[16]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[16]  <= rx_data_l_shift[16];
  assign rx_data_l[16] = \rx_data_l_reg[16] ;
  reg \rx_data_l_reg[17]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[17]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[17]  <= rx_data_l_shift[17];
  assign rx_data_l[17] = \rx_data_l_reg[17] ;
  reg \rx_data_l_reg[18]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[18]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[18]  <= rx_data_l_shift[18];
  assign rx_data_l[18] = \rx_data_l_reg[18] ;
  reg \rx_data_l_reg[19]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[19]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[19]  <= rx_data_l_shift[19];
  assign rx_data_l[19] = \rx_data_l_reg[19] ;
  reg \rx_data_l_reg[20]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[20]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[20]  <= rx_data_l_shift[20];
  assign rx_data_l[20] = \rx_data_l_reg[20] ;
  reg \rx_data_l_reg[21]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[21]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[21]  <= rx_data_l_shift[21];
  assign rx_data_l[21] = \rx_data_l_reg[21] ;
  reg \rx_data_l_reg[22]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[22]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[22]  <= rx_data_l_shift[22];
  assign rx_data_l[22] = \rx_data_l_reg[22] ;
  reg \rx_data_l_reg[23]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_l_reg[23]  <= 1'h0;
    else if (_064_) \rx_data_l_reg[23]  <= rx_data_l_shift[23];
  assign rx_data_l[23] = \rx_data_l_reg[23] ;
  reg \rx_data_r_reg[0]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[0]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[0]  <= rx_data_r_shift[0];
  assign rx_data_r[0] = \rx_data_r_reg[0] ;
  reg \rx_data_r_reg[1]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[1]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[1]  <= rx_data_r_shift[1];
  assign rx_data_r[1] = \rx_data_r_reg[1] ;
  reg \rx_data_r_reg[2]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[2]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[2]  <= rx_data_r_shift[2];
  assign rx_data_r[2] = \rx_data_r_reg[2] ;
  reg \rx_data_r_reg[3]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[3]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[3]  <= rx_data_r_shift[3];
  assign rx_data_r[3] = \rx_data_r_reg[3] ;
  reg \rx_data_r_reg[4]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[4]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[4]  <= rx_data_r_shift[4];
  assign rx_data_r[4] = \rx_data_r_reg[4] ;
  reg \rx_data_r_reg[5]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[5]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[5]  <= rx_data_r_shift[5];
  assign rx_data_r[5] = \rx_data_r_reg[5] ;
  reg \rx_data_r_reg[6]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[6]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[6]  <= rx_data_r_shift[6];
  assign rx_data_r[6] = \rx_data_r_reg[6] ;
  reg \rx_data_r_reg[7]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[7]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[7]  <= rx_data_r_shift[7];
  assign rx_data_r[7] = \rx_data_r_reg[7] ;
  reg \rx_data_r_reg[8]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[8]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[8]  <= rx_data_r_shift[8];
  assign rx_data_r[8] = \rx_data_r_reg[8] ;
  reg \rx_data_r_reg[9]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[9]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[9]  <= rx_data_r_shift[9];
  assign rx_data_r[9] = \rx_data_r_reg[9] ;
  reg \rx_data_r_reg[10]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[10]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[10]  <= rx_data_r_shift[10];
  assign rx_data_r[10] = \rx_data_r_reg[10] ;
  reg \rx_data_r_reg[11]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[11]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[11]  <= rx_data_r_shift[11];
  assign rx_data_r[11] = \rx_data_r_reg[11] ;
  reg \rx_data_r_reg[12]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[12]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[12]  <= rx_data_r_shift[12];
  assign rx_data_r[12] = \rx_data_r_reg[12] ;
  reg \rx_data_r_reg[13]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[13]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[13]  <= rx_data_r_shift[13];
  assign rx_data_r[13] = \rx_data_r_reg[13] ;
  reg \rx_data_r_reg[14]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[14]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[14]  <= rx_data_r_shift[14];
  assign rx_data_r[14] = \rx_data_r_reg[14] ;
  reg \rx_data_r_reg[15]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[15]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[15]  <= rx_data_r_shift[15];
  assign rx_data_r[15] = \rx_data_r_reg[15] ;
  reg \rx_data_r_reg[16]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[16]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[16]  <= rx_data_r_shift[16];
  assign rx_data_r[16] = \rx_data_r_reg[16] ;
  reg \rx_data_r_reg[17]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[17]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[17]  <= rx_data_r_shift[17];
  assign rx_data_r[17] = \rx_data_r_reg[17] ;
  reg \rx_data_r_reg[18]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[18]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[18]  <= rx_data_r_shift[18];
  assign rx_data_r[18] = \rx_data_r_reg[18] ;
  reg \rx_data_r_reg[19]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[19]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[19]  <= rx_data_r_shift[19];
  assign rx_data_r[19] = \rx_data_r_reg[19] ;
  reg \rx_data_r_reg[20]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[20]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[20]  <= rx_data_r_shift[20];
  assign rx_data_r[20] = \rx_data_r_reg[20] ;
  reg \rx_data_r_reg[21]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[21]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[21]  <= rx_data_r_shift[21];
  assign rx_data_r[21] = \rx_data_r_reg[21] ;
  reg \rx_data_r_reg[22]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[22]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[22]  <= rx_data_r_shift[22];
  assign rx_data_r[22] = \rx_data_r_reg[22] ;
  reg \rx_data_r_reg[23]  = 1'h0;
  (* src = "axis_i2s2.v:130.11-137.12" *)
  always @(posedge axis_clk)
    if (!axis_resetn) \rx_data_r_reg[23]  <= 1'h0;
    else if (_064_) \rx_data_r_reg[23]  <= rx_data_r_shift[23];
  assign rx_data_r[23] = \rx_data_r_reg[23] ;
  (* src = "axis_i2s2.v:141.11-147.37" *)
  always @(posedge axis_clk)
    if (!axis_resetn) rx_axis_p_valid <= 1'h0;
    else if (_000_) rx_axis_p_valid <= _064_;
  (* src = "axis_i2s2.v:149.11-155.47" *)
  always @(posedge axis_clk)
    if (_008_) rx_axis_p_last <= 1'h0;
    else if (_065_) rx_axis_p_last <= _066_;
  assign _113_[8:1] = count[8:1];
  assign _114_[0] = _113_[0];
  assign din_sync = din_sync_shift[2];
  assign lrck = count[8];
  assign mclk = axis_clk;
  assign rx_axis_p_data[31:24] = 8'h00;
  assign rx_data_l[31:24] = 8'h00;
  assign rx_data_r[31:24] = 8'h00;
  assign rx_lrck = count[8];
  assign rx_mclk = axis_clk;
  assign rx_sclk = count[2];
  assign sclk = count[2];
  assign tx_data_l[31:24] = 8'hxx;
  assign tx_data_r[31:24] = 8'hxx;
  assign tx_lrck = count[8];
  assign tx_mclk = axis_clk;
  assign tx_sclk = count[2];
endmodule
