/* Generated by Yosys 0.39 (git sha1 00338082b, aarch64-apple-darwin21.4-clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* hdlname = "bsg_serial_in_parallel_out_full" *)
(* src = "bsg_serial_in_parallel_out_full.sv:18.8-18.39" *)
module sipo(clk_i, reset_i, v_i, ready_and_o, v_o, ready_i, \data_o[1] , data_i, \data_o[0] );
  reg _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  (* hdlname = "brr clk_i" *)
  (* src = "bsg_round_robin_1_to_n.sv:17.12-17.17" *)
  wire \brr.clk_i ;
  (* hdlname = "brr one_to_n.circular_ptr add_i" *)
  (* src = "bsg_circular_ptr.sv:18.40-18.45" *)
  wire \brr.one_to_n.circular_ptr.add_i ;
  (* hdlname = "brr one_to_n.circular_ptr clk" *)
  (* src = "bsg_circular_ptr.sv:16.11-16.14" *)
  wire \brr.one_to_n.circular_ptr.clk ;
  (* hdlname = "brr one_to_n.circular_ptr genblk1.genblk1.ptr_r_p1" *)
  (* src = "bsg_circular_ptr.sv:54.33-54.41" *)
  wire \brr.one_to_n.circular_ptr.genblk1.genblk1.ptr_r_p1 ;
  (* hdlname = "brr one_to_n.circular_ptr o" *)
  (* src = "bsg_circular_ptr.sv:19.33-19.34" *)
  wire \brr.one_to_n.circular_ptr.o ;
  (* hdlname = "brr one_to_n.circular_ptr ptr_r" *)
  (* src = "bsg_circular_ptr.sv:23.29-23.34" *)
  reg \brr.one_to_n.circular_ptr.ptr_r ;
  (* hdlname = "brr one_to_n.circular_ptr reset_i" *)
  (* src = "bsg_circular_ptr.sv:17.13-17.20" *)
  wire \brr.one_to_n.circular_ptr.reset_i ;
  (* hdlname = "brr one_to_n.ptr_r" *)
  (* src = "bsg_round_robin_1_to_n.sv:40.46-40.51" *)
  wire \brr.one_to_n.ptr_r ;
  (* hdlname = "brr one_to_n.yumi_li" *)
  (* src = "bsg_round_robin_1_to_n.sv:42.13-42.20" *)
  wire \brr.one_to_n.yumi_li ;
  (* hdlname = "brr ready_and_o" *)
  (* src = "bsg_round_robin_1_to_n.sv:22.27-22.38" *)
  wire \brr.ready_and_o ;
  (* hdlname = "brr reset_i" *)
  (* src = "bsg_round_robin_1_to_n.sv:18.14-18.21" *)
  wire \brr.reset_i ;
  (* hdlname = "brr valid_i" *)
  (* src = "bsg_round_robin_1_to_n.sv:21.27-21.34" *)
  wire \brr.valid_i ;
  (* src = "bsg_serial_in_parallel_out_full.sv:26.10-26.15" *)
  input clk_i;
  wire clk_i;
  (* src = "bsg_serial_in_parallel_out_full.sv:31.42-31.48" *)
  input [23:0] data_i;
  wire [23:0] data_i;
  (* src = "bsg_serial_in_parallel_out_full.sv:43.34-43.41" *)
  wire [23:0] \data_lo[0] ;
  (* src = "bsg_serial_in_parallel_out_full.sv:43.34-43.41" *)
  wire [23:0] \data_lo[1] ;
  (* src = "bsg_serial_in_parallel_out_full.sv:33.42-33.48" *)
  output [23:0] \data_o[0] ;
  wire [23:0] \data_o[0] ;
  (* src = "bsg_serial_in_parallel_out_full.sv:33.42-33.48" *)
  output [23:0] \data_o[1] ;
  wire [23:0] \data_o[1] ;
  (* src = "bsg_serial_in_parallel_out_full.sv:62.21-62.34" *)
  (* unused_bits = "0" *)
  wire [1:0] fifo_valid_lo;
  (* hdlname = "fifos[0].twofifo.fifo clk_i" *)
  (* src = "bsg_two_fifo.sv:36.11-36.16" *)
  wire \fifos[0].twofifo.fifo.clk_i ;
  (* hdlname = "fifos[0].twofifo.fifo data_i" *)
  (* src = "bsg_two_fifo.sv:41.27-41.33" *)
  wire [23:0] \fifos[0].twofifo.fifo.data_i ;
  (* hdlname = "fifos[0].twofifo.fifo data_o" *)
  (* src = "bsg_two_fifo.sv:46.27-46.33" *)
  wire [23:0] \fifos[0].twofifo.fifo.data_o ;
  (* hdlname = "fifos[0].twofifo.fifo deq_i" *)
  (* src = "bsg_two_fifo.sv:50.9-50.14" *)
  wire \fifos[0].twofifo.fifo.deq_i ;
  (* hdlname = "fifos[0].twofifo.fifo empty_r" *)
  (* src = "bsg_two_fifo.sv:54.27-54.34" *)
  reg \fifos[0].twofifo.fifo.empty_r ;
  (* hdlname = "fifos[0].twofifo.fifo enq_i" *)
  (* src = "bsg_two_fifo.sv:51.9-51.14" *)
  wire \fifos[0].twofifo.fifo.enq_i ;
  (* hdlname = "fifos[0].twofifo.fifo full_r" *)
  (* src = "bsg_two_fifo.sv:54.36-54.42" *)
  reg \fifos[0].twofifo.fifo.full_r ;
  (* hdlname = "fifos[0].twofifo.fifo head_r" *)
  (* src = "bsg_two_fifo.sv:53.27-53.33" *)
  reg \fifos[0].twofifo.fifo.head_r ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w r_addr_i" *)
  (* src = "bsg_mem_1r1w.sv:25.34-25.42" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.r_addr_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w r_data_o" *)
  (* src = "bsg_mem_1r1w.sv:27.52-27.60" *)
  wire [23:0] \fifos[0].twofifo.fifo.mem_1r1w.r_data_o ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w r_v_i" *)
  (* src = "bsg_mem_1r1w.sv:24.34-24.39" *)
  (* unused_bits = "0" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.r_v_i ;
  reg [23:0] \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] ;
  reg [23:0] \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth nz.r_addr_li" *)
  (* src = "bsg_mem_1r1w_synth.sv:45.28-45.37" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.r_addr_li ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth nz.w_addr_li" *)
  (* src = "bsg_mem_1r1w_synth.sv:46.28-46.37" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.w_addr_li ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth r_addr_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:27.31-27.39" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.r_addr_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth r_data_o" *)
  (* src = "bsg_mem_1r1w_synth.sv:29.49-29.57" *)
  wire [23:0] \fifos[0].twofifo.fifo.mem_1r1w.synth.r_data_o ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth r_v_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:26.10-26.15" *)
  (* unused_bits = "0" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.r_v_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth unused0" *)
  (* src = "bsg_mem_1r1w_synth.sv:32.8-32.15" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.unused0 ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth unused1" *)
  (* src = "bsg_mem_1r1w_synth.sv:33.8-33.15" *)
  (* unused_bits = "0" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.unused1 ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth w_addr_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:22.30-22.38" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.w_addr_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth w_clk_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:18.9-18.16" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.w_clk_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth w_data_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:23.42-23.50" *)
  wire [23:0] \fifos[0].twofifo.fifo.mem_1r1w.synth.w_data_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth w_reset_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:19.10-19.19" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.w_reset_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w synth w_v_i" *)
  (* src = "bsg_mem_1r1w_synth.sv:21.10-21.15" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.synth.w_v_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w w_addr_i" *)
  (* src = "bsg_mem_1r1w.sv:20.33-20.41" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.w_addr_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w w_clk_i" *)
  (* src = "bsg_mem_1r1w.sv:16.13-16.20" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.w_clk_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w w_data_i" *)
  (* src = "bsg_mem_1r1w.sv:21.51-21.59" *)
  wire [23:0] \fifos[0].twofifo.fifo.mem_1r1w.w_data_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w w_reset_i" *)
  (* src = "bsg_mem_1r1w.sv:17.13-17.22" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.w_reset_i ;
  (* hdlname = "fifos[0].twofifo.fifo mem_1r1w w_v_i" *)
  (* src = "bsg_mem_1r1w.sv:19.33-19.38" *)
  wire \fifos[0].twofifo.fifo.mem_1r1w.w_v_i ;
  (* hdlname = "fifos[0].twofifo.fifo reset_i" *)
  (* src = "bsg_two_fifo.sv:37.13-37.20" *)
  wire \fifos[0].twofifo.fifo.reset_i ;
  (* hdlname = "fifos[0].twofifo.fifo tail_r" *)
  (* src = "bsg_two_fifo.sv:53.36-53.42" *)
  reg \fifos[0].twofifo.fifo.tail_r ;
  (* hdlname = "fifos[0].twofifo.fifo v_o" *)
  (* src = "bsg_two_fifo.sv:45.27-45.30" *)
  (* unused_bits = "0" *)
  wire \fifos[0].twofifo.fifo.v_o ;
  (* hdlname = "fifos[0].twofifo.fifo yumi_i" *)
  (* src = "bsg_two_fifo.sv:47.27-47.33" *)
  wire \fifos[0].twofifo.fifo.yumi_i ;
  (* hdlname = "fifos[1].onefifo.fifo clk_i" *)
  (* src = "bsg_one_fifo.sv:21.11-21.16" *)
  wire \fifos[1].onefifo.fifo.clk_i ;
  (* hdlname = "fifos[1].onefifo.fifo data_i" *)
  (* src = "bsg_one_fifo.sv:26.27-26.33" *)
  wire [23:0] \fifos[1].onefifo.fifo.data_i ;
  (* hdlname = "fifos[1].onefifo.fifo data_o" *)
  (* src = "bsg_one_fifo.sv:31.27-31.33" *)
  wire [23:0] \fifos[1].onefifo.fifo.data_o ;
  (* hdlname = "fifos[1].onefifo.fifo dff clk_i" *)
  (* src = "bsg_dff_en.sv:12.9-12.14" *)
  wire \fifos[1].onefifo.fifo.dff.clk_i ;
  (* hdlname = "fifos[1].onefifo.fifo dff data_i" *)
  (* src = "bsg_dff_en.sv:13.24-13.30" *)
  wire [23:0] \fifos[1].onefifo.fifo.dff.data_i ;
  (* hdlname = "fifos[1].onefifo.fifo dff data_o" *)
  (* src = "bsg_dff_en.sv:15.31-15.37" *)
  wire [23:0] \fifos[1].onefifo.fifo.dff.data_o ;
  (* hdlname = "fifos[1].onefifo.fifo dff data_r" *)
  (* src = "bsg_dff_en.sv:18.23-18.29" *)
  reg [23:0] \fifos[1].onefifo.fifo.dff.data_r ;
  (* hdlname = "fifos[1].onefifo.fifo dff en_i" *)
  (* src = "bsg_dff_en.sv:14.10-14.14" *)
  wire \fifos[1].onefifo.fifo.dff.en_i ;
  (* hdlname = "fifos[1].onefifo.fifo dff_full clk_i" *)
  (* src = "bsg_dff_reset.sv:4.13-4.18" *)
  wire \fifos[1].onefifo.fifo.dff_full.clk_i ;
  (* hdlname = "fifos[1].onefifo.fifo dff_full data_i" *)
  (* src = "bsg_dff_reset.sv:6.27-6.33" *)
  wire \fifos[1].onefifo.fifo.dff_full.data_i ;
  (* hdlname = "fifos[1].onefifo.fifo dff_full data_o" *)
  (* src = "bsg_dff_reset.sv:7.27-7.33" *)
  wire \fifos[1].onefifo.fifo.dff_full.data_o ;
  (* hdlname = "fifos[1].onefifo.fifo dff_full data_r" *)
  (* src = "bsg_dff_reset.sv:10.22-10.28" *)
  reg \fifos[1].onefifo.fifo.dff_full.data_r ;
  (* hdlname = "fifos[1].onefifo.fifo dff_full reset_i" *)
  (* src = "bsg_dff_reset.sv:5.12-5.19" *)
  wire \fifos[1].onefifo.fifo.dff_full.reset_i ;
  (* hdlname = "fifos[1].onefifo.fifo full_r" *)
  (* src = "bsg_one_fifo.sv:35.21-35.27" *)
  wire \fifos[1].onefifo.fifo.full_r ;
  (* hdlname = "fifos[1].onefifo.fifo reset_i" *)
  (* src = "bsg_one_fifo.sv:22.13-22.20" *)
  wire \fifos[1].onefifo.fifo.reset_i ;
  (* hdlname = "fifos[1].onefifo.fifo v_o" *)
  (* src = "bsg_one_fifo.sv:30.27-30.30" *)
  wire \fifos[1].onefifo.fifo.v_o ;
  (* hdlname = "fifos[1].onefifo.fifo yumi_i" *)
  (* src = "bsg_one_fifo.sv:32.27-32.33" *)
  wire \fifos[1].onefifo.fifo.yumi_i ;
  (* src = "bsg_serial_in_parallel_out_full.sv:30.42-30.53" *)
  output ready_and_o;
  wire ready_and_o;
  (* src = "bsg_serial_in_parallel_out_full.sv:35.42-35.49" *)
  input ready_i;
  wire ready_i;
  (* src = "bsg_serial_in_parallel_out_full.sv:27.10-27.17" *)
  input reset_i;
  wire reset_i;
  (* src = "bsg_serial_in_parallel_out_full.sv:29.42-29.45" *)
  input v_i;
  wire v_i;
  (* src = "bsg_serial_in_parallel_out_full.sv:34.42-34.45" *)
  output v_o;
  wire v_o;
  (* src = "bsg_serial_in_parallel_out_full.sv:40.13-40.19" *)
  wire yumi_i;
  assign \brr.one_to_n.circular_ptr.genblk1.genblk1.ptr_r_p1  = ~\brr.one_to_n.circular_ptr.ptr_r ;
  assign v_o = \fifos[1].onefifo.fifo.dff_full.data_r  & ~(\fifos[0].twofifo.fifo.empty_r );
  assign _019_ = ~\fifos[1].onefifo.fifo.dff_full.data_r ;
  assign _008_ = ~\fifos[0].twofifo.fifo.full_r ;
  assign ready_and_o = \brr.one_to_n.circular_ptr.ptr_r  ? _019_ : _008_;
  assign _003_ = ~\fifos[0].twofifo.fifo.head_r ;
  assign \fifos[0].twofifo.fifo.deq_i  = v_o & ready_i;
  assign _002_ = \fifos[0].twofifo.fifo.deq_i  ^ \fifos[0].twofifo.fifo.head_r ;
  assign \data_o[0] [0] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [0] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [0];
  assign \data_o[0] [1] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [1] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [1];
  assign \data_o[0] [2] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [2] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [2];
  assign \data_o[0] [3] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [3] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [3];
  assign \data_o[0] [4] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [4] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [4];
  assign \data_o[0] [5] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [5] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [5];
  assign \data_o[0] [6] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [6] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [6];
  assign \data_o[0] [7] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [7] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [7];
  assign \data_o[0] [8] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [8] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [8];
  assign \data_o[0] [9] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [9] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [9];
  assign \data_o[0] [10] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [10] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [10];
  assign \data_o[0] [11] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [11] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [11];
  assign \data_o[0] [12] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [12] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [12];
  assign \data_o[0] [13] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [13] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [13];
  assign \data_o[0] [14] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [14] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [14];
  assign \data_o[0] [15] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [15] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [15];
  assign \data_o[0] [16] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [16] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [16];
  assign \data_o[0] [17] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [17] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [17];
  assign \data_o[0] [18] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [18] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [18];
  assign \data_o[0] [19] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [19] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [19];
  assign \data_o[0] [20] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [20] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [20];
  assign \data_o[0] [21] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [21] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [21];
  assign \data_o[0] [22] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [22] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [22];
  assign \data_o[0] [23] = _000_ ? \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [23] : \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [23];
  assign _009_ = ~(v_o & ready_i);
  assign _010_ = v_i & \brr.one_to_n.circular_ptr.ptr_r ;
  assign \fifos[1].onefifo.fifo.dff_full.data_i  = \fifos[1].onefifo.fifo.dff_full.data_r  ? _009_ : _010_;
  assign _001_ = ~\fifos[0].twofifo.fifo.tail_r ;
  assign _011_ = \brr.one_to_n.circular_ptr.ptr_r  | ~(v_i);
  assign \fifos[0].twofifo.fifo.enq_i  = _008_ & ~(_011_);
  assign \brr.one_to_n.circular_ptr.add_i  = ready_and_o & v_i;
  assign _012_ = _011_ | \fifos[0].twofifo.fifo.full_r ;
  assign _006_ = _001_ & ~(_012_);
  assign _013_ = _012_ | \fifos[0].twofifo.fifo.empty_r ;
  assign _014_ = _009_ & ~(_013_);
  assign _015_ = \fifos[0].twofifo.fifo.full_r  & ~(\fifos[0].twofifo.fifo.deq_i );
  assign _005_ = _015_ | _014_;
  assign _016_ = \fifos[0].twofifo.fifo.empty_r  & ~(\fifos[0].twofifo.fifo.enq_i );
  assign _017_ = _009_ | \fifos[0].twofifo.fifo.full_r ;
  assign _018_ = _012_ & ~(_017_);
  assign _004_ = _018_ | _016_;
  assign _007_ = \fifos[0].twofifo.fifo.tail_r  & ~(_012_);
  assign \fifos[1].onefifo.fifo.dff.en_i  = _010_ & ~(\fifos[1].onefifo.fifo.dff_full.data_r );
  (* src = "bsg_circular_ptr.sv:32.14-34.32" *)
  always @(posedge clk_i)
    if (reset_i) \brr.one_to_n.circular_ptr.ptr_r  <= 1'h0;
    else if (\brr.one_to_n.circular_ptr.add_i ) \brr.one_to_n.circular_ptr.ptr_r  <= \brr.one_to_n.circular_ptr.genblk1.genblk1.ptr_r_p1 ;
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [0] <= data_i[0];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [1] <= data_i[1];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [2] <= data_i[2];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [3] <= data_i[3];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [4] <= data_i[4];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [5] <= data_i[5];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [6] <= data_i[6];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [7] <= data_i[7];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [8] <= data_i[8];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [9] <= data_i[9];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [10] <= data_i[10];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [11] <= data_i[11];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [12] <= data_i[12];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [13] <= data_i[13];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [14] <= data_i[14];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [15] <= data_i[15];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [16] <= data_i[16];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [17] <= data_i[17];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [18] <= data_i[18];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [19] <= data_i[19];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [20] <= data_i[20];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [21] <= data_i[21];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [22] <= data_i[22];
  always @(posedge clk_i)
    if (_006_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[0] [23] <= data_i[23];
  (* src = "bsg_two_fifo.sv:78.14-106.9" *)
  always @(posedge clk_i)
    if (reset_i) \fifos[0].twofifo.fifo.empty_r  <= 1'h1;
    else \fifos[0].twofifo.fifo.empty_r  <= _004_;
  (* src = "bsg_two_fifo.sv:78.14-106.9" *)
  always @(posedge clk_i)
    if (reset_i) \fifos[0].twofifo.fifo.head_r  <= 1'h0;
    else if (\fifos[0].twofifo.fifo.deq_i ) \fifos[0].twofifo.fifo.head_r  <= _003_;
  (* src = "bsg_two_fifo.sv:78.14-106.9" *)
  always @(posedge clk_i)
    if (reset_i) \fifos[0].twofifo.fifo.tail_r  <= 1'h0;
    else if (\fifos[0].twofifo.fifo.enq_i ) \fifos[0].twofifo.fifo.tail_r  <= _001_;
  always @(posedge clk_i)
    if (reset_i) _000_ <= 1'h0;
    else _000_ <= _002_;
  (* src = "bsg_dff_reset.sv:14.11-20.9" *)
  always @(posedge clk_i)
    if (reset_i) \fifos[1].onefifo.fifo.dff_full.data_r  <= 1'h0;
    else \fifos[1].onefifo.fifo.dff_full.data_r  <= \fifos[1].onefifo.fifo.dff_full.data_i ;
  (* src = "bsg_two_fifo.sv:78.14-106.9" *)
  always @(posedge clk_i)
    if (reset_i) \fifos[0].twofifo.fifo.full_r  <= 1'h0;
    else \fifos[0].twofifo.fifo.full_r  <= _005_;
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [0] <= data_i[0];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [1] <= data_i[1];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [2] <= data_i[2];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [3] <= data_i[3];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [4] <= data_i[4];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [5] <= data_i[5];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [6] <= data_i[6];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [7] <= data_i[7];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [8] <= data_i[8];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [9] <= data_i[9];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [10] <= data_i[10];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [11] <= data_i[11];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [12] <= data_i[12];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [13] <= data_i[13];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [14] <= data_i[14];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [15] <= data_i[15];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [16] <= data_i[16];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [17] <= data_i[17];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [18] <= data_i[18];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [19] <= data_i[19];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [20] <= data_i[20];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [21] <= data_i[21];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [22] <= data_i[22];
  (* src = "bsg_dff_en.sv:22.13-26.6" *)
  always @(posedge clk_i)
    if (\fifos[1].onefifo.fifo.dff.en_i ) \fifos[1].onefifo.fifo.dff.data_r [23] <= data_i[23];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [0] <= data_i[0];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [1] <= data_i[1];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [2] <= data_i[2];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [3] <= data_i[3];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [4] <= data_i[4];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [5] <= data_i[5];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [6] <= data_i[6];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [7] <= data_i[7];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [8] <= data_i[8];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [9] <= data_i[9];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [10] <= data_i[10];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [11] <= data_i[11];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [12] <= data_i[12];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [13] <= data_i[13];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [14] <= data_i[14];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [15] <= data_i[15];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [16] <= data_i[16];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [17] <= data_i[17];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [18] <= data_i[18];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [19] <= data_i[19];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [20] <= data_i[20];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [21] <= data_i[21];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [22] <= data_i[22];
  always @(posedge clk_i)
    if (_007_) \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.mem[1] [23] <= data_i[23];
  assign \brr.clk_i  = clk_i;
  assign \brr.one_to_n.circular_ptr.clk  = clk_i;
  assign \brr.one_to_n.circular_ptr.o  = \brr.one_to_n.circular_ptr.ptr_r ;
  assign \brr.one_to_n.circular_ptr.reset_i  = reset_i;
  assign \brr.one_to_n.ptr_r  = \brr.one_to_n.circular_ptr.ptr_r ;
  assign \brr.one_to_n.yumi_li  = \brr.one_to_n.circular_ptr.add_i ;
  assign \brr.ready_and_o  = ready_and_o;
  assign \brr.reset_i  = reset_i;
  assign \brr.valid_i  = v_i;
  assign \data_lo[0]  = \data_o[0] ;
  assign \data_lo[1]  = \fifos[1].onefifo.fifo.dff.data_r ;
  assign \data_o[1]  = \fifos[1].onefifo.fifo.dff.data_r ;
  assign fifo_valid_lo[1] = \fifos[1].onefifo.fifo.dff_full.data_r ;
  assign \fifos[0].twofifo.fifo.clk_i  = clk_i;
  assign \fifos[0].twofifo.fifo.data_i  = data_i;
  assign \fifos[0].twofifo.fifo.data_o  = \data_o[0] ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.r_addr_i  = \fifos[0].twofifo.fifo.head_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.r_data_o  = \data_o[0] ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.r_v_i  = fifo_valid_lo[0];
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.r_addr_li  = \fifos[0].twofifo.fifo.head_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.nz.w_addr_li  = \fifos[0].twofifo.fifo.tail_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.r_addr_i  = \fifos[0].twofifo.fifo.head_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.r_data_o  = \data_o[0] ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.r_v_i  = fifo_valid_lo[0];
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.unused0  = reset_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.unused1  = fifo_valid_lo[0];
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.w_addr_i  = \fifos[0].twofifo.fifo.tail_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.w_clk_i  = clk_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.w_data_i  = data_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.w_reset_i  = reset_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.synth.w_v_i  = \fifos[0].twofifo.fifo.enq_i ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.w_addr_i  = \fifos[0].twofifo.fifo.tail_r ;
  assign \fifos[0].twofifo.fifo.mem_1r1w.w_clk_i  = clk_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.w_data_i  = data_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.w_reset_i  = reset_i;
  assign \fifos[0].twofifo.fifo.mem_1r1w.w_v_i  = \fifos[0].twofifo.fifo.enq_i ;
  assign \fifos[0].twofifo.fifo.reset_i  = reset_i;
  assign \fifos[0].twofifo.fifo.v_o  = fifo_valid_lo[0];
  assign \fifos[0].twofifo.fifo.yumi_i  = \fifos[0].twofifo.fifo.deq_i ;
  assign \fifos[1].onefifo.fifo.clk_i  = clk_i;
  assign \fifos[1].onefifo.fifo.data_i  = data_i;
  assign \fifos[1].onefifo.fifo.data_o  = \fifos[1].onefifo.fifo.dff.data_r ;
  assign \fifos[1].onefifo.fifo.dff.clk_i  = clk_i;
  assign \fifos[1].onefifo.fifo.dff.data_i  = data_i;
  assign \fifos[1].onefifo.fifo.dff.data_o  = \fifos[1].onefifo.fifo.dff.data_r ;
  assign \fifos[1].onefifo.fifo.dff_full.clk_i  = clk_i;
  assign \fifos[1].onefifo.fifo.dff_full.data_o  = \fifos[1].onefifo.fifo.dff_full.data_r ;
  assign \fifos[1].onefifo.fifo.dff_full.reset_i  = reset_i;
  assign \fifos[1].onefifo.fifo.full_r  = \fifos[1].onefifo.fifo.dff_full.data_r ;
  assign \fifos[1].onefifo.fifo.reset_i  = reset_i;
  assign \fifos[1].onefifo.fifo.v_o  = \fifos[1].onefifo.fifo.dff_full.data_r ;
  assign \fifos[1].onefifo.fifo.yumi_i  = \fifos[0].twofifo.fifo.deq_i ;
  assign yumi_i = \fifos[0].twofifo.fifo.deq_i ;
endmodule
